name: nero_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.3
  - pip
  - pip:
    - numpy==1.23.5
    - scipy==1.9.3
    - scikit-image==0.19.3
    - h5py==3.7.0
    - opencv-python==4.6.0.66
    - scikit-learn==1.1.3
    - pandas==1.5.3
    - open3d==0.16.0
    - tensorboardX
    - PyMCubes
    - plyfile
    - transforms3d
    - tqdm
    - PyYAML
    - trimesh
    - xatlas
    - dearpygui